language: python
env:
  global:
    - secure: "bQPjiDjSbYfFHGdCZNFCZAJpoPlSu7IAAkkOEFrUzj4YhYwGn2w61zIWoAW4gkqqyLQI5oFv8Bu3kooL/IRGo5BX6GCoZFLTwq8basQppHSuR5GYldGk6iWIOoPSAHZ2cK/E5lTZvgcuoh1O+Il0gE/o4IW2UnSixLVk3l1Ul+U="
    - secure: "YnQ/rBUSpl+zQjtn6YD9yNqEcOFYba9ML/XuHMojBfjQvs2WDXSpQ1cJfM82Bi+R6G+uXEFZ+yl4w9UDSl/V3pXLd/JUYNUHXbvfhwoRsbe2hWzaBIrOE8GXftFxwSbK+fUc3uWC5DKOQ59EpqGUoUat1S5yKhfEvX2mk4bZuzI="
    - secure: "VRDkV99gkXu8eIiXJ1+Fmd68UL6gQAp6ycA8nP6QIiVurz9Xfn4A6n6gbx3yKjdOQ4CUxrJkdx7qouHsWcduMaiFAbQaSA4uafLhRECKLD/ZkeogWS+kVKbkT1IXQHZ1mThrpymovpiFbh4e4fwXcExAmpywcHODK5N0Gr2CfaY="
python:
  - 2.7
install:
  - pip install -r requirements.txt
script:
  - rm -rf build/ tmp/
  - sphinx-build -aE -nW -b html -d tmp docs-en/source/ build/en
  - sphinx-build -aE -nW -b html -d tmp docs-fr/source/ build/fr
after_success:
  - openssl aes-256-cbc -K $encrypted_9f7cba75ae55_key -iv $encrypted_9f7cba75ae55_iv -in .travis.deploy.enc -out .travis.deploy -d
  - chmod 600 .travis.deploy
  - eval "$(ssh-agent -s)"
  - ssh-add .travis.deploy
  - rsync -e "ssh -o StrictHostKeyChecking=no" -az --force --delete build/ "$DEPLOY_USER"@"$DEPLOY_IP":"$DEPLOY_PATH"
sudo: false

